/**
 * analysis/import-blocks: unmanaged coverage records -> Terraform 1.5+ `import {}` blocks.
 *
 * PURE. No I/O — returns the `.tf` text; the CLI decides whether/where to write it. Each
 * UNMANAGED record becomes an import block Terraform can consume to bring the resource under
 * IaC. Import-ID formats confirmed against okta/okta v4.20.0 (see PLAN.md step-1 findings):
 * single id for most kinds, `<app_id>/<group_id>` for the SINGULAR app-group assignment.
 */

import type { ParsedResource } from "../core/parse-tfstate.js";
import type { CoverageReport } from "./coverage.js";

/** Kind -> Terraform resource type. Apps are excluded — they carry their own `appType`. */
const KIND_TO_TF_TYPE: Record<Exclude<ParsedResource["kind"], "App">, string> = {
  Group: "okta_group",
  GroupRule: "okta_group_rule",
  GlobalSessionPolicy: "okta_policy_signon",
  AppAuthPolicy: "okta_app_signon_policy",
  // Assignment gaps target the SINGULAR resource (one block per pair); the plural imports by
  // app id and would pull ALL groups, wrong granularity for a per-pair gap.
  AppGroupAssignment: "okta_app_group_assignment",
};

const UNKNOWN_APP_PREFIX = "okta_app_unknown:";

/** display name -> a valid HCL resource label (lowercase, `[^a-z0-9_]`->`_`, non-digit start). */
function sanitizeLabel(name: string): string {
  let s = name.toLowerCase().replace(/[^a-z0-9_]/g, "_");
  if (s === "") s = "resource";
  if (/^[0-9]/.test(s)) s = `_${s}`;
  return s;
}

/** id -> display name for Groups and Apps, used to label assignment blocks `<app>_<group>`. */
function nameMapFrom(resources: ParsedResource[]): Map<string, string> {
  const names = new Map<string, string>();
  for (const r of resources) {
    if (r.kind === "Group" || r.kind === "App") names.set(r.id, r.name);
  }
  return names;
}

function importId(r: ParsedResource): string {
  return r.kind === "AppGroupAssignment" ? `${r.appId}/${r.groupId}` : r.id;
}

function baseLabel(r: ParsedResource, names: Map<string, string>): string {
  if (r.kind === "AppGroupAssignment") {
    const app = sanitizeLabel(names.get(r.appId) ?? r.appId);
    const group = sanitizeLabel(names.get(r.groupId) ?? r.groupId);
    return `${app}_${group}`;
  }
  return sanitizeLabel(r.name);
}

const HEADER = [
  "# Terraform import blocks generated by okta-iac-lens (M3 coverage).",
  "# Review, add to your config, then run `terraform plan` to preview the import.",
].join("\n");

/**
 * Generate `import {}` blocks for every UNMANAGED record in `report`. `live` resolves
 * app/group display names for assignment labels. An App whose type couldn't be mapped
 * (`okta_app_unknown:<mode>`) gets a commented-out block naming the mode — never a guess.
 */
export function generateImportBlocks(report: CoverageReport, live: ParsedResource[]): string {
  const names = nameMapFrom(live);
  const unmanaged = report.items.filter((i) => i.bucket === "unmanaged").map((i) => i.resource);

  if (unmanaged.length === 0) {
    return `${HEADER}\n\n# No unmanaged resources — nothing to import.\n`;
  }

  // Dedupe `to` addresses: two records that sanitize to the same label get _2, _3, ...
  const usedAddresses = new Set<string>();
  const uniqueLabel = (type: string, base: string): string => {
    let label = base;
    let n = 2;
    while (usedAddresses.has(`${type}.${label}`)) label = `${base}_${n++}`;
    usedAddresses.add(`${type}.${label}`);
    return label;
  };

  const blocks = unmanaged.map((r) => {
    const base = baseLabel(r, names);
    const id = importId(r);

    if (r.kind === "App" && r.appType.startsWith(UNKNOWN_APP_PREFIX)) {
      const mode = r.appType.slice(UNKNOWN_APP_PREFIX.length);
      return [
        `# Unmapped app sign-on mode ${JSON.stringify(mode)} for app ${JSON.stringify(r.name)} (${r.id}).`,
        "# Set the correct okta_app_* resource type manually, then uncomment:",
        "# import {",
        `#   to = okta_app_<TYPE>.${base}`,
        `#   id = ${JSON.stringify(id)}`,
        "# }",
      ].join("\n");
    }

    const type = r.kind === "App" ? r.appType : KIND_TO_TF_TYPE[r.kind];
    const label = uniqueLabel(type, base);
    return ["import {", `  to = ${type}.${label}`, `  id = ${JSON.stringify(id)}`, "}"].join("\n");
  });

  return `${HEADER}\n\n${blocks.join("\n\n")}\n`;
}
